Add SourceAddress optional override on serializer and UseCloudEvents
riezebosch/MassTransit.CloudEvents pull request #9
Opened 2022-11-04 09:58 UTC by Powdor42

- Add SourceAddress optional override on serializer and UseCloudEvents
- Allways return full Uri (not relative)
- Testing all GetSourceAddress options

2022-11-04 10:15 UTC, wim-jan commented on Rebus/CloudEventify.Rebus/Factory.cs
> +    public static CustomTypeNameConventionBuilder UseCloudEvents(this StandardConfigurer<ISerializer> configurer, JsonSerializerOptions? options = null, Uri? soureAddress = null)
```suggestion
    public static CustomTypeNameConventionBuilder UseCloudEvents(this StandardConfigurer<ISerializer> configurer, JsonSerializerOptions? options = null, Uri? sourceAddress = null)
```

2022-11-04 10:15 UTC, wim-jan commented on Rebus/CloudEventify.Rebus/Factory.cs
> +        configurer.Register(c => new Serializer(Formatter.New(options), options, c.Get<IMessageTypeNameConvention>(), soureAddress));
```suggestion
        configurer.Register(c => new Serializer(Formatter.New(options), options, c.Get<IMessageTypeNameConvention>(), sourceAddress));
```

2022-11-04 10:28 UTC, riezebosch requested changes
I do agree that setting the source is helpful, but there are some doubts about the current implementation. The `InternalsVisibleTo` is a smell to me, I'd rather validate on the public API. Also bringing in AutoFixture for a single object creation seems a bit overkill (at this point, at least). 

Probably a much cleaner solution would be injecting a step into the pipeline that sets the source header for it to be picked up by the serializer? 

```csharp
.Options(o => o.UseSourceAddress(new Uri("https://some-uri/"))
```

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerSourceAddressTests.cs
> +            _simpleBaseMessage.Headers.Add(Headers.SenderAddress, "things");
I would like you to put this into a factory method instead of the constructor initializing a field

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerSourceAddressTests.cs
> +            var sut = (ISerializer)new Serializer(_formatter, new JsonSerializerOptions(), _messageTypeNameConventionMock.Object, fact);
FluentAssertions has the beautiful extension method `.As<T>()` for this

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerSourceAddressTests.cs
> +            cloudEvent.Should().NotBeNull();
null checking is superfluous, FluentAssertions already does that for you.

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerSourceAddressTests.cs
> +            if (_simpleBaseMessage.Headers.ContainsKey(Headers.SenderAddress))
I don't understand if-statements inside a (unit) test?

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerTests.cs
> +            .Any(x => x.Id == 1234);
you could probably check the `MessageContext` here to make it even a better test

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus/Factory.cs
> +    public static void InjectMessageId(this OptionsConfigurer configurer) =>
unrelated

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus/Factory.cs
> +    public static void UseCustomTypeNameForTopicName(this OptionsConfigurer configurer) =>
unrelated

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus/Serializer.cs
> +    private readonly JsonSerializerOptions _jsonSerializerOptions;
why change this?

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus/Serializer.cs
> +            Subject = message.GetMessageLabel(),
unrelated?!

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/CloudEventify.Rebus.Tests.csproj
> +        <PackageReference Include="AutoFixture" Version="4.17.0" />
I'd rather use [Bogus](https://github.com/bchavez/Bogus).

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerSourceAddressTests.cs
> +            _simpleBaseMessage.Headers.Add(Headers.SenderAddress, "things");
That is, all fields can be removed and let the factory method just return an initialized serializer.

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/SerializerSourceAddressTests.cs
> +            _messageTypeNameConventionMock = new Mock<IMessageTypeNameConvention>();
don't postfix

2022-11-04 10:28 UTC, riezebosch commented on Rebus/CloudEventify.Rebus.Tests/CloudEventify.Rebus.Tests.csproj
> +        <PackageReference Include="Moq" Version="4.18.2" />
for such simple scenarios I'd prefer `NSubstitute` over `Moq`

2022-11-07 08:14 UTC, riezebosch commented
Using the `sent` address makes sense because it requires sensible names for the `queue` to be used which is a good idea in itself. For `OneWay` clients we could add the `Option` to inject the `sent-address` with a custom value later on.

2022-11-07 08:14 UTC, closed without merging